export interface CurrencyData {}
export interface FragmentData {}
export interface OilData {}
export interface ScarabData {}
export interface FossilData {}
export interface EssenceData {}
export interface DivinationCardData {}
export interface SkillGemData {}
export interface BaseTypeData {}
export interface UniqueMapData {}
export interface UniqueJewelData {}
export interface UniqueFlaskData {}
export interface UniqueWeaponData {}
export interface UniqueArmourData {}
export interface UniqueAccessoryData {}
